#!/bin/bash
# monitor_parallel_runs.sh
#
# Week 5-6 Monitoring: Automated daily validation runs
# Executes comparison script and tracks trends over time
#
# Usage:
#   ./monitor_parallel_runs.sh           # Run once (manual mode)
#   ./monitor_parallel_runs.sh --daily   # Set up daily automation (macOS launchd)
#   ./monitor_parallel_runs.sh --status  # Check monitoring status

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
COMPARISON_SCRIPT="$SCRIPT_DIR/compare_legacy_vs_new.R"
VALIDATION_DIR="$PROJECT_ROOT/validation"
LOG_FILE="$VALIDATION_DIR/monitoring.log"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Ensure validation directory exists
mkdir -p "$VALIDATION_DIR"

# Logging function
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Run validation
run_validation() {
    log "=== Starting parallel running validation ==="
    log "Working directory: $PROJECT_ROOT"

    cd "$PROJECT_ROOT"

    if [ ! -f "$COMPARISON_SCRIPT" ]; then
        log "ERROR: Comparison script not found at $COMPARISON_SCRIPT"
        exit 1
    fi

    # Run the R script
    log "Executing comparison script..."
    if Rscript "$COMPARISON_SCRIPT" >> "$LOG_FILE" 2>&1; then
        log "✓ Validation completed successfully"
        RESULT_STATUS="SUCCESS"
    else
        EXIT_CODE=$?
        log "⚠ Validation completed with warnings (exit code: $EXIT_CODE)"
        RESULT_STATUS="WARNING"
    fi

    # Find latest report
    LATEST_REPORT=$(ls -t "$VALIDATION_DIR"/parallel_run_report_*.md 2>/dev/null | head -n 1)
    LATEST_CSV=$(ls -t "$VALIDATION_DIR"/parallel_run_*.csv 2>/dev/null | head -n 1)

    if [ -n "$LATEST_REPORT" ]; then
        log "Report generated: $LATEST_REPORT"
    fi

    if [ -n "$LATEST_CSV" ]; then
        log "Data saved: $LATEST_CSV"

        # Extract summary from CSV
        PASS_COUNT=$(grep -c ",PASS," "$LATEST_CSV" || echo "0")
        WARNING_COUNT=$(grep -c ",WARNING," "$LATEST_CSV" || echo "0")
        FAIL_COUNT=$(grep -c ",FAIL," "$LATEST_CSV" || echo "0")

        log "Summary: PASS=$PASS_COUNT, WARNING=$WARNING_COUNT, FAIL=$FAIL_COUNT"
    fi

    log "=== Validation run complete ==="
    echo ""
}

# Generate trend report
generate_trend_report() {
    log "Generating trend analysis..."

    cd "$PROJECT_ROOT"

    # Count number of validation runs
    RUN_COUNT=$(ls -1 "$VALIDATION_DIR"/parallel_run_*.csv 2>/dev/null | wc -l | tr -d ' ')

    if [ "$RUN_COUNT" -eq 0 ]; then
        log "No validation runs found yet"
        return
    fi

    log "Total validation runs: $RUN_COUNT"

    # Create trend report
    TREND_REPORT="$VALIDATION_DIR/trend_analysis.md"

    cat > "$TREND_REPORT" <<'EOF'
# Parallel Running Trend Analysis

## Overview

This report tracks validation results over time during the Week 5-6 parallel running phase.

## Validation History

| Date | PASS | WARNING | FAIL | INFO | Overall Status |
|------|------|---------|------|------|----------------|
EOF

    # Analyze each CSV file
    for csv_file in $(ls -t "$VALIDATION_DIR"/parallel_run_*.csv 2>/dev/null); do
        DATE=$(basename "$csv_file" | sed 's/parallel_run_//' | sed 's/.csv//')
        PASS=$(grep -c ",PASS," "$csv_file" || echo "0")
        WARNING=$(grep -c ",WARNING," "$csv_file" || echo "0")
        FAIL=$(grep -c ",FAIL," "$csv_file" || echo "0")
        INFO=$(grep -c ",INFO," "$csv_file" || echo "0")

        # Determine overall status
        if [ "$FAIL" -gt 1 ]; then
            OVERALL="FAIL"
        elif [ "$FAIL" -eq 1 ] || [ "$WARNING" -gt 2 ]; then
            OVERALL="WARNING"
        else
            OVERALL="PASS"
        fi

        echo "| $DATE | $PASS | $WARNING | $FAIL | $INFO | $OVERALL |" >> "$TREND_REPORT"
    done

    cat >> "$TREND_REPORT" <<EOF

## Key Metrics

- **Total Runs**: $RUN_COUNT
- **Monitoring Period**: $(ls -t "$VALIDATION_DIR"/parallel_run_*.csv | tail -n 1 | xargs basename | sed 's/parallel_run_//' | sed 's/.csv//') to $(date +%Y-%m-%d)

## Compliance Tracking

### R116: Variable Range Metadata (CRITICAL INNOVATION)
- Schema validated and ready for sales data integration

### R117: Time Series Transparency
- All required transparency markers present
- Currently in placeholder mode

### R118: Statistical Significance Documentation
- All required documentation fields present
- Schema ready for sales data

## Next Steps

1. Continue daily monitoring through Week 6
2. Integrate sales data to activate full analysis
3. Prepare for Week 7 cutover decision

---

*Last updated: $(date)*
*Generated by: monitor_parallel_runs.sh*
EOF

    log "✓ Trend report saved to: $TREND_REPORT"
}

# Set up daily automation (macOS launchd)
setup_daily_automation() {
    log "Setting up daily automation..."

    PLIST_NAME="com.mamba.parallel_running"
    PLIST_FILE="$HOME/Library/LaunchAgents/${PLIST_NAME}.plist"

    # Create LaunchAgents directory if it doesn't exist
    mkdir -p "$HOME/Library/LaunchAgents"

    # Create plist file
    cat > "$PLIST_FILE" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${PLIST_NAME}</string>

    <key>ProgramArguments</key>
    <array>
        <string>$SCRIPT_DIR/monitor_parallel_runs.sh</string>
    </array>

    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>9</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>

    <key>StandardOutPath</key>
    <string>$VALIDATION_DIR/launchd_stdout.log</string>

    <key>StandardErrorPath</key>
    <string>$VALIDATION_DIR/launchd_stderr.log</string>

    <key>WorkingDirectory</key>
    <string>$PROJECT_ROOT</string>
</dict>
</plist>
EOF

    # Load the plist
    launchctl unload "$PLIST_FILE" 2>/dev/null || true
    launchctl load "$PLIST_FILE"

    log "✓ Daily automation configured"
    log "  Schedule: Every day at 09:00"
    log "  Plist: $PLIST_FILE"
    log "  To disable: launchctl unload $PLIST_FILE"
}

# Check monitoring status
check_status() {
    echo "=== Parallel Running Monitoring Status ==="
    echo ""
    echo "Project Root: $PROJECT_ROOT"
    echo "Validation Dir: $VALIDATION_DIR"
    echo ""

    # Count validation runs
    RUN_COUNT=$(ls -1 "$VALIDATION_DIR"/parallel_run_*.csv 2>/dev/null | wc -l | tr -d ' ')
    echo "Total Validation Runs: $RUN_COUNT"

    if [ "$RUN_COUNT" -gt 0 ]; then
        echo ""
        echo "Recent Runs:"
        ls -lt "$VALIDATION_DIR"/parallel_run_*.csv | head -n 5 | awk '{print "  " $9 " (" $6, $7, $8 ")"}'

        echo ""
        echo "Latest Report:"
        LATEST_REPORT=$(ls -t "$VALIDATION_DIR"/parallel_run_report_*.md 2>/dev/null | head -n 1)
        if [ -n "$LATEST_REPORT" ]; then
            echo "  $LATEST_REPORT"

            # Extract overall status from latest report
            if grep -q "Overall Status.*PASS" "$LATEST_REPORT"; then
                echo -e "  Status: ${GREEN}PASS${NC}"
            elif grep -q "Overall Status.*WARNING" "$LATEST_REPORT"; then
                echo -e "  Status: ${YELLOW}WARNING${NC}"
            elif grep -q "Overall Status.*FAIL" "$LATEST_REPORT"; then
                echo -e "  Status: ${RED}FAIL${NC}"
            fi
        fi
    fi

    echo ""
    echo "Daily Automation:"
    PLIST_NAME="com.mamba.parallel_running"
    PLIST_FILE="$HOME/Library/LaunchAgents/${PLIST_NAME}.plist"

    if [ -f "$PLIST_FILE" ]; then
        if launchctl list | grep -q "$PLIST_NAME"; then
            echo -e "  ${GREEN}Enabled${NC} (runs daily at 09:00)"
        else
            echo -e "  ${YELLOW}Configured but not loaded${NC}"
        fi
    else
        echo -e "  ${YELLOW}Not configured${NC} (run with --daily to enable)"
    fi

    echo ""
    echo "Files:"
    echo "  Comparison Script: $COMPARISON_SCRIPT"
    echo "  Log File: $LOG_FILE"

    if [ -f "$VALIDATION_DIR/trend_analysis.md" ]; then
        echo "  Trend Report: $VALIDATION_DIR/trend_analysis.md"
    fi
}

# Main execution
case "${1:-}" in
    --daily)
        run_validation
        generate_trend_report
        setup_daily_automation
        ;;
    --status)
        check_status
        ;;
    --help)
        echo "Usage: $0 [--daily|--status|--help]"
        echo ""
        echo "Options:"
        echo "  (no args)  Run validation once (manual mode)"
        echo "  --daily    Run validation and set up daily automation"
        echo "  --status   Check monitoring status"
        echo "  --help     Show this help message"
        ;;
    *)
        run_validation
        generate_trend_report
        ;;
esac

exit 0
